# Generated by Django 5.1.6 on 2025-09-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True, verbose_name='Is approved'),
        ),
    ]
