# Generated by Django 5.2.6 on 2025-11-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_delete_media',
            field=models.BooleanField(default=False, verbose_name='DC SM can delete media'),
        ),
    ]
