# Generated by Django 5.1.6 on 2025-03-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('identity_providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Display name for this login option (e.g. Login through DEIC)', max_length=100)),
                ('url', models.CharField(help_text='URL or path for this login option', max_length=255)),
                ('ordering', models.PositiveIntegerField(default=0, help_text='Display order (smaller numbers appear first)')),
                ('active', models.BooleanField(default=True, help_text='Whether this login option is currently active')),
            ],
            options={
                'verbose_name': 'Login Option',
                'verbose_name_plural': 'Login Options',
                'ordering': ['ordering'],
            },
        ),
    ]
