# Generated by Django 5.1.6 on 2025-03-25 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('identity_providers', '0002_loginoption'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='identityprovidercategorymapping',
            unique_together=set(),
        ),
    ]
