# Generated by Django 5.1.6 on 2025-03-25 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('files', '0005_alter_category_uid'),
        ('identity_providers', '0003_alter_identityprovidercategorymapping_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityprovidercategorymapping',
            name='map_to',
            field=models.ForeignKey(help_text='Category id', on_delete=django.db.models.deletion.CASCADE, to='files.category'),
        ),
    ]
