FROM mediacms/mediacms:latest

SHELL ["/bin/bash", "-c"]

# Set up virtualenv
ENV VIRTUAL_ENV=/home/mediacms.io
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
ENV PIP_NO_CACHE_DIR=1

RUN cd /home/mediacms.io && python3 -m venv $VIRTUAL_ENV

COPY requirements.txt . 
COPY requirements-dev.txt .
RUN pip install -r requirements-dev.txt

WORKDIR /home/mediacms.io/mediacms
