[pytest]
DJANGO_SETTINGS_MODULE = cms.test_settings
python_files = test_*.py
norecursedirs = .git .venv node_modules frontend frontend-tools media_files static static_collected logs lms-plugins moodle docs

markers =
    slow: slow running test
