# Generated by Django 5.1.6 on 2025-03-11 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SAMLConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remove_from_groups', models.BooleanField(default=False, help_text='Automatically remove from groups')),
                ('save_saml_response_logs', models.BooleanField(default=True)),
                ('sso_url', models.URLField(help_text='Sign-in URL')),
                ('slo_url', models.URLField(help_text='Sign-out URL')),
                ('sp_metadata_url', models.URLField(help_text='https://host/saml/metadata')),
                ('idp_id', models.URLField(help_text='Identity Provider ID')),
                ('idp_cert', models.TextField(help_text='x509cert')),
                ('uid', models.CharField(help_text='eg eduPersonPrincipalName', max_length=100)),
                ('name', models.CharField(blank=True, help_text='eg displayName', max_length=100, null=True)),
                ('email', models.CharField(blank=True, help_text='eg mail', max_length=100, null=True)),
                ('groups', models.CharField(blank=True, help_text='eg isMemberOf', max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, help_text='eg gn', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, help_text='eg sn', max_length=100, null=True)),
                ('user_logo', models.CharField(blank=True, help_text='eg jpegPhoto', max_length=100, null=True)),
                ('role', models.CharField(blank=True, help_text='eduPersonPrimaryAffiliation', max_length=100, null=True)),
                ('verified_email', models.BooleanField(default=False, help_text='Mark email as verified')),
                ('email_authentication', models.BooleanField(default=False, help_text='Use email authentication too')),
                ('social_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saml_configurations', to='socialaccount.socialapp')),
            ],
            options={
                'verbose_name': 'SAML Configuration',
                'verbose_name_plural': 'SAML Configurations',
                'unique_together': {('social_app', 'idp_id')},
            },
        ),
        migrations.CreateModel(
            name='SAMLLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logs', models.TextField(blank=True, null=True)),
                ('social_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saml_logs', to='socialaccount.socialapp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saml_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SAML Log',
                'verbose_name_plural': 'SAML Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SAMLConfigurationGlobalRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='SAML value', max_length=100, verbose_name='Global Role Mapping')),
                (
                    'map_to',
                    models.CharField(
                        choices=[
                            ('user', 'Authenticated User'),
                            ('advancedUser', 'Advanced User'),
                            ('editor', 'MediaCMS Editor'),
                            ('manager', 'MediaCMS Manager'),
                            ('admin', 'MediaCMS Administrator'),
                        ],
                        help_text='MediaCMS Global Role',
                        max_length=20,
                    ),
                ),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_roles', to='saml_auth.samlconfiguration')),
            ],
            options={
                'verbose_name': 'SAML Global Role Mapping',
                'verbose_name_plural': 'SAML Global Role Mappings',
                'unique_together': {('configuration', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SAMLConfigurationGroupMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='SAML value', max_length=100, verbose_name='Group name')),
                ('map_to', models.CharField(help_text='MediaCMS Group name', max_length=300)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_mapping', to='saml_auth.samlconfiguration')),
            ],
            options={
                'verbose_name': 'SAML Group Mapping',
                'verbose_name_plural': 'SAML Group Mappings',
                'unique_together': {('configuration', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SAMLConfigurationGroupRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='SAML value', max_length=100, verbose_name='Group Role Mapping')),
                ('map_to', models.CharField(choices=[('member', 'Member'), ('contributor', 'Contributor'), ('manager', 'Manager')], help_text='MediaCMS Group Role', max_length=20)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_roles', to='saml_auth.samlconfiguration')),
            ],
            options={
                'verbose_name': 'SAML Group Role Mapping',
                'verbose_name_plural': 'SAML Group Role Mappings',
                'unique_together': {('configuration', 'name')},
            },
        ),
    ]
