# Generated by Django 5.2.6 on 2026-05-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saml_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samlconfiguration',
            name='sp_cert',
            field=models.TextField(blank=True, help_text='SP x509cert (PEM). Optional; required if SP private key is set.', null=True),
        ),
        migrations.AddField(
            model_name='samlconfiguration',
            name='sp_private_key',
            field=models.TextField(blank=True, help_text='SP private key (PEM). Optional; required if SP certificate is set.', null=True),
        ),
    ]
