# Generated by Django 5.1.6 on 2025-02-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saml_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samlconfiguration',
            name='email_authentication',
            field=models.BooleanField(default=True, help_text='Use email authentication too'),
        ),
        migrations.AddField(
            model_name='samlconfiguration',
            name='verified_email',
            field=models.BooleanField(default=True, help_text='Mark email as verified'),
        ),
    ]
