# Generated by Django 5.1.6 on 2025-03-05 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saml_auth', '0002_samlconfiguration_email_authentication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAMLConfigurationGlobalRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='SAML value', max_length=100, unique=True, verbose_name='Global Role Mapping')),
                ('map_to', models.CharField(choices=[('advancedUser', 'Advanced User'), ('editor', 'MediaCMS Editor'), ('manager', 'MediaCMS Manager')], help_text='MediaCMS Global Role', max_length=20)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_roles', to='saml_auth.samlconfiguration')),
            ],
            options={
                'verbose_name': 'SAML Global Role Mapping',
                'verbose_name_plural': 'SAML Global Role Mappings',
            },
        ),
        migrations.CreateModel(
            name='SAMLConfigurationGroupMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='SAML value', max_length=100, unique=True, verbose_name='Group name')),
                ('map_to', models.CharField(help_text='MediaCMS Group name', max_length=300)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_mapping', to='saml_auth.samlconfiguration')),
            ],
            options={
                'verbose_name': 'SAML Group Mapping',
                'verbose_name_plural': 'SAML Group Mappings',
            },
        ),
        migrations.CreateModel(
            name='SAMLConfigurationGroupRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='SAML value', max_length=100, unique=True, verbose_name='Group Role Mapping')),
                ('map_to', models.CharField(choices=[('member', 'Member'), ('contributor', 'Contributor'), ('manager', 'Manager')], help_text='MediaCMS Group Role', max_length=20)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_roles', to='saml_auth.samlconfiguration')),
            ],
            options={
                'verbose_name': 'SAML Group Role Mapping',
                'verbose_name_plural': 'SAML Group Role Mappings',
            },
        ),
    ]
