# Generated by Django 5.1.6 on 2025-03-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saml_auth', '0003_samlconfigurationglobalrole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samlconfigurationglobalrole',
            name='name',
            field=models.CharField(help_text='SAML value', max_length=100, verbose_name='Global Role Mapping'),
        ),
        migrations.AlterField(
            model_name='samlconfigurationgroupmapping',
            name='name',
            field=models.CharField(help_text='SAML value', max_length=100, verbose_name='Group name'),
        ),
        migrations.AlterField(
            model_name='samlconfigurationgrouprole',
            name='name',
            field=models.CharField(help_text='SAML value', max_length=100, verbose_name='Group Role Mapping'),
        ),
        migrations.AlterUniqueTogether(
            name='samlconfigurationglobalrole',
            unique_together={('configuration', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='samlconfigurationgroupmapping',
            unique_together={('configuration', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='samlconfigurationgrouprole',
            unique_together={('configuration', 'name')},
        ),
    ]
