# Generated by Django 5.1.6 on 2025-03-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saml_auth', '0004_alter_samlconfigurationglobalrole_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samlconfigurationglobalrole',
            name='map_to',
            field=models.CharField(choices=[('advancedUser', 'Advanced User'), ('editor', 'MediaCMS Editor'), ('manager', 'MediaCMS Manager'), ('admin', 'MediaCMS Administrator')], help_text='MediaCMS Global Role', max_length=20),
        ),
    ]
