# Generated by Django 5.1.6 on 2025-03-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saml_auth', '0005_alter_samlconfigurationglobalrole_map_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samlconfigurationglobalrole',
            name='map_to',
            field=models.CharField(choices=[('user', 'Authenticated User'), ('advancedUser', 'Advanced User'), ('editor', 'MediaCMS Editor'), ('manager', 'MediaCMS Manager'), ('admin', 'MediaCMS Administrator')], help_text='MediaCMS Global Role', max_length=20),
        ),
    ]
