# Generated by Django 5.1.6 on 2025-03-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saml_auth', '0007_remove_samlconfiguration_create_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samlconfiguration',
            name='email_authentication',
            field=models.BooleanField(default=False, help_text='Use email authentication too'),
        ),
        migrations.AlterField(
            model_name='samlconfiguration',
            name='verified_email',
            field=models.BooleanField(default=False, help_text='Mark email as verified'),
        ),
    ]
