# Generated by Django 5.2.6 on 2026-01-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='output_file',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
