# Generated by Django 3.1.4 on 2020-12-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="for not logged in users",
                        max_length=33,
                        null=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("dislike", "Dislike"),
                            ("watch", "Watch"),
                            ("report", "Report"),
                            ("rate", "Rate"),
                        ],
                        default="watch",
                        max_length=20,
                    ),
                ),
                ("extra_info", models.TextField(blank=True, null=True)),
                ("action_date", models.DateTimeField(auto_now_add=True)),
                ("remote_ip", models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
