export const sampleGlobalMediaCMS = {
    profileId: 'john',
    site: {
        id: 'my-site',
        url: 'https://example.com/',
        api: 'https://example.com/api/',
        title: 'Example',
        theme: { mode: 'dark', switch: { enabled: true, position: 'sidebar' } },
        logo: {
            lightMode: { img: '/img/light.png', svg: '/img/light.svg' },
            darkMode: { img: '/img/dark.png', svg: '/img/dark.svg' },
        },
        devEnv: false,
        useRoundedCorners: true,
        version: '1.0.0',
        taxonomies: {
            tags: { enabled: true, title: 'Topic Tags' },
            categories: { enabled: false, title: 'Kinds' },
        },
        pages: {
            featured: { enabled: true, title: 'Featured picks' },
            latest: { enabled: true, title: 'Recent uploads' },
            members: { enabled: true, title: 'People' },
            recommended: { enabled: false, title: 'You may like' },
        },
        userPages: {
            liked: { enabled: true, title: 'Favorites' },
            history: { enabled: true, title: 'Watched' },
        },
    },
    url: {
        home: '/',
        admin: '/admin',
        error404: '/404',
        latestMedia: '/latest',
        featuredMedia: '/featured',
        recommendedMedia: '/recommended',
        signin: '/signin',
        signout: '/signout',
        register: '/register',
        changePassword: '/password',
        members: '/members',
        search: '/search',
        likedMedia: '/liked',
        history: '/history',
        addMedia: '/add',
        editChannel: '/edit/channel',
        editProfile: '/edit/profile',
        tags: '/tags',
        categories: '/categories',
        manageMedia: '/manage/media',
        manageUsers: '/manage/users',
        manageComments: '/manage/comments',
    },
    api: {
        media: 'v1/media/',
        playlists: 'v1/playlists',
        members: 'v1/users',
        liked: 'v1/user/liked',
        history: 'v1/user/history',
        tags: 'v1/tags',
        categories: 'v1/categories',
        manage_media: 'v1/manage/media',
        manage_users: 'v1/manage/users',
        manage_comments: 'v1/manage/comments',
        search: 'v1/search',
        actions: 'v1/actions',
        comments: 'v1/comments',
    },
    contents: {
        header: {
            right: '',
            onLogoRight: '',
        },
        notifications: {
            messages: { addToLiked: 'Yay', removeFromLiked: 'Oops', addToDisliked: 'nay', removeFromDisliked: 'ok' },
        },
        sidebar: {
            belowNavMenu: '__belowNavMenu__',
            belowThemeSwitcher: '__belowThemeSwitcher__',
            footer: '__footer__',
            mainMenuExtraItems: [
                { text: '__text_1__', link: '__link_1__', icon: '__icon_1__', className: '__className_1__' },
            ],
            navMenuItems: [
                { text: '__text_2__', link: '__link_2__', icon: '__icon_2__', className: '__className_2__' },
            ],
        },
        uploader: {
            belowUploadArea: '__belowUploadArea__',
            postUploadMessage: '__postUploadMessage__',
        },
    },
    pages: {
        home: {
            sections: {
                latest: { title: 'Latest T' },
                featured: { title: 'Featured T' },
                recommended: { title: 'Recommended T' },
            },
        },
        media: { categoriesWithTitle: true, htmlInDescription: true, hideViews: true, related: { initialSize: 5 } },
        profile: { htmlInDescription: true, includeHistory: true, includeLikedMedia: true },
        search: { advancedFilters: true },
    },
    features: {
        mediaItem: { hideAuthor: true, hideViews: false, hideDate: true },
        media: {
            actions: {
                like: true,
                dislike: true,
                report: true,
                comment: true,
                comment_mention: true,
                download: true,
                save: true,
                share: true,
            },
            shareOptions: ['embed', 'email'],
        },
        playlists: { mediaTypes: ['audio'] },
        sideBar: { hideHomeLink: false, hideTagsLink: true, hideCategoriesLink: false },
        embeddedVideo: { initialDimensions: { width: 640, height: 360 } },
        headerBar: { hideLogin: false, hideRegister: true },
    },
    user: {
        is: { anonymous: false, admin: true },
        name: ' John ',
        username: ' john ',
        thumbnail: ' /img/j.png ',
        can: {
            changePassword: true,
            deleteProfile: true,
            addComment: true,
            mentionComment: true,
            deleteComment: true,
            editMedia: true,
            deleteMedia: true,
            editSubtitle: true,
            manageMedia: true,
            manageUsers: true,
            manageComments: true,
            contactUser: true,
            canSeeMembersPage: true,
            usersNeedsToBeApproved: false,
            addMedia: true,
            editProfile: true,
            readComment: true,
        },
        pages: { about: '/u/john/about ', media: '/u/john ', playlists: '/u/john/playlists ' },
    },
};

export const sampleMediaCMSConfig = {
    api: {
        archive: {
            tags: '',
            categories: '',
        },
        featured: '',
        manage: {
            media: '',
            users: '',
            comments: '',
        },
        media: '',
        playlists: '/v1/playlists',
        recommended: '',
        search: {
            query: '',
            titles: './search.html?titles=',
            tag: '',
            category: '',
        },
        user: {
            liked: '',
            history: '',
            playlists: '/playlists/?author=',
        },
        users: '/users',
    },
    contents: {
        header: {
            right: '',
            onLogoRight: '',
        },
        uploader: {
            belowUploadArea: '',
            postUploadMessage: '',
        },
        sidebar: {
            belowNavMenu: '__belowNavMenu__',
            belowThemeSwitcher: '__belowThemeSwitcher__',
            footer: '__footer__',
            mainMenuExtra: {
                items: [{ text: '__text_1__', link: '__link_1__', icon: '__icon_1__', className: '__className_1__' }],
            },
            navMenu: {
                items: [{ text: '__text_2__', link: '__link_2__', icon: '__icon_2__', className: '__className_2__' }],
            },
        },
    },
    enabled: {
        taxonomies: sampleGlobalMediaCMS.site.taxonomies,
        pages: {
            featured: { enabled: true, title: 'Featured picks' },
            latest: { enabled: true, title: 'Recent uploads' },
            members: { enabled: true, title: 'People' },
            recommended: { enabled: true, title: 'You may like' },
            liked: { enabled: true, title: 'Favorites' },
            history: { enabled: true, title: 'Watched' },
        },
    },
    member: {
        name: null,
        username: 'john',
        thumbnail: null,
        is: {
            admin: false,
            anonymous: false,
        },
        can: {
            addComment: false,
            addMedia: false,
            canSeeMembersPage: false,
            changePassword: false,
            contactUser: false,
            deleteComment: false,
            deleteMedia: false,
            deleteProfile: false,
            dislikeMedia: false,
            downloadMedia: false,
            editMedia: false,
            editProfile: false,
            editSubtitle: false,
            likeMedia: false,
            login: false,
            manageComments: false,
            manageMedia: false,
            manageUsers: false,
            mentionComment: false,
            readComment: true,
            register: false,
            reportMedia: false,
            saveMedia: true,
            shareMedia: false,
            usersNeedsToBeApproved: false,
        },
        pages: {
            home: null,
            about: null,
            media: null,
            playlists: null,
        },
    },
    media: {
        item: {
            displayAuthor: false,
            displayViews: false,
            displayPublishDate: false,
        },
        share: {
            options: [],
        },
    },
    notifications: {
        messages: {
            addToLiked: '',
            removeFromLiked: '',
            addToDisliked: '',
            removeFromDisliked: '',
        },
    },
    options: {
        pages: {
            home: {
                sections: {
                    latest: {
                        title: '',
                    },
                    featured: {
                        title: '',
                    },
                    recommended: {
                        title: '',
                    },
                },
            },
            search: {
                advancedFilters: false,
            },
            media: {
                categoriesWithTitle: true,
                htmlInDescription: true,
                related: { initialSize: 5 },
                displayViews: true,
            },
            profile: {
                htmlInDescription: false,
                includeHistory: false,
                includeLikedMedia: false,
            },
        },
        embedded: {
            video: {
                dimensions: {
                    width: 0,
                    widthUnit: 'px',
                    height: 0,
                    heightUnit: 'px',
                },
            },
        },
    },
    playlists: {
        mediaTypes: [],
    },
    sidebar: {
        hideHomeLink: false,
        hideTagsLink: false,
        hideCategoriesLink: false,
    },
    site: {
        api: '',
        id: '',
        title: '',
        url: '',
        useRoundedCorners: false,
        version: '',
    },
    theme: {
        logo: {
            lightMode: { img: '/img/light.png', svg: '/img/light.svg' },
            darkMode: { img: '/img/dark.png', svg: '/img/dark.svg' },
        },
        mode: 'dark',
        switch: {
            enabled: true,
            position: 'sidebar',
        },
    },
    url: {
        admin: '',
        archive: {
            categories: '',
            tags: '',
        },
        changePassword: '',
        embed: '',
        error404: '',
        featured: '',
        home: '',
        latest: '',
        manage: {
            comments: '',
            media: '',
            users: '',
        },
        members: '',
        profile: {
            about: '',
            media: '',
            playlists: '',
            shared_by_me: '',
            shared_with_me: '',
        },
        recommended: '',
        register: '',
        search: {
            base: '',
            category: '',
            query: '',
            tag: '',
        },
        signin: '',
        signout: '',
        user: {
            addMedia: '',
            editChannel: '',
            editProfile: '',
            history: '',
            liked: '',
        },
    },
};
