# Generated by Django 5.1.6 on 2025-03-25 14:18

from django.db import migrations, models

import rbac.models


class Migration(migrations.Migration):
    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbacgroup',
            name='uid',
            field=models.CharField(default=rbac.models.generate_uid, help_text='Unique identifier for the RBAC group (unique per identity provider)', max_length=255),
        ),
    ]
