# Generated by Django 3.1.8 on 2021-06-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20201201_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encodeprofile',
            name='resolution',
            field=models.IntegerField(blank=True, choices=[(2160, '2160'), (1530, '1530'), (1520, '1520'), (1440, '1440'), (1080, '1080'), (720, '720'), (480, '480'), (360, '360'), (240, '240')], null=True),
        ),
    ]
