# Generated by Django 5.1.6 on 2025-03-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('files', '0003_auto_20210927_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtitle',
            options={'ordering': ['language__title']},
        ),
        migrations.AddField(
            model_name='category',
            name='is_rbac_category',
            field=models.BooleanField(db_index=True, default=False, help_text='If Category is part of the Role Based Access Control system'),
        ),
    ]
