# Generated by Django 5.1.6 on 2025-03-18 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('files', '0003_auto_20210927_1245'),
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtitle',
            options={'ordering': ['language__title']},
        ),
        migrations.AddField(
            model_name='category',
            name='identity_provider',
            field=models.ForeignKey(
                blank=True,
                help_text='If category is related with a specific Identity Provider',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='categories',
                to='socialaccount.socialapp',
                verbose_name='IDP Config Name',
            ),
        ),
        migrations.AddField(
            model_name='category',
            name='is_rbac_category',
            field=models.BooleanField(db_index=True, default=False, help_text='If access to Category is controlled by role based membership of Groups'),
        ),
        migrations.AlterField(
            model_name='media',
            name='state',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('unlisted', 'Unlisted')], db_index=True, default='private', help_text='state of Media', max_length=20),
        ),
    ]
