# Generated by Django 5.1.6 on 2025-02-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20210927_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_rbac_category',
            field=models.BooleanField(default=False, help_text='If Category is part of the RBAC system'),
        ),
        migrations.AlterField(
            model_name='media',
            name='state',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('unlisted', 'Unlisted')], db_index=True, default='private', help_text='state of Media', max_length=20),
        ),
    ]
