# Generated by Django 5.1.6 on 2025-03-25 14:13

from django.db import migrations, models

import files.models


class Migration(migrations.Migration):
    dependencies = [
        ('files', '0004_alter_subtitle_options_category_identity_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='uid',
            field=models.CharField(default=files.models.generate_uid, max_length=36, unique=True),
        ),
    ]
