# Generated by Django 5.1.6 on 2025-02-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_category_is_rbac_category_alter_media_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_rbac_category',
            field=models.BooleanField(db_index=True, default=False, help_text='If Category is part of the RBAC system'),
        ),
    ]
