# Generated by Django 5.1.6 on 2025-03-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('files', '0005_alter_category_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
