# Generated by Django 5.1.6 on 2025-03-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_alter_category_is_rbac_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_rbac_category',
            field=models.BooleanField(db_index=True, default=False, help_text='If Category is part of the Role Based Access Control system'),
        ),
    ]
