# Generated by Django 5.1.6 on 2025-04-15 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('files', '0006_alter_category_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoChapterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(help_text='Chapter data')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='files.media')),
            ],
            options={
                'unique_together': {('media',)},
            },
        ),
    ]
