# Generated by Django 5.1.6 on 2025-06-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('files', '0008_alter_media_state_videotrimrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='friendly_token',
            field=models.CharField(blank=True, db_index=True, help_text='Identifier for the Media', max_length=150, unique=True),
        ),
    ]
