# Generated by Django 5.1.6 on 2025-07-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('files', '0009_alter_media_friendly_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encodeprofile',
            name='resolution',
            field=models.IntegerField(blank=True, choices=[(2160, '2160'), (1440, '1440'), (1080, '1080'), (720, '720'), (480, '480'), (360, '360'), (240, '240'), (144, '144')], null=True),
        ),
    ]
