# Generated by Django 5.1.6 on 2025-08-31 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('files', '0011_mediapermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(help_text='language code', max_length=30),
        ),
        migrations.AddField(
            model_name='media',
            name='allow_whisper_transcribe',
            field=models.BooleanField(default=False, verbose_name='Transcribe auto-detected language'),
        ),
        migrations.AddField(
            model_name='media',
            name='allow_whisper_transcribe_and_translate',
            field=models.BooleanField(default=False, verbose_name='Transcribe auto-detected language and translate to English'),
        ),
        migrations.CreateModel(
            name='TranscriptionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('fail', 'Fail'), ('success', 'Success')], db_index=True, default='pending', max_length=20)),
                ('translate_to_english', models.BooleanField(default=False)),
                ('logs', models.TextField(blank=True, null=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptionrequests', to='files.media')),
            ],
        ),
    ]
