# Generated by Django 5.2.6 on 2025-11-22 01:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_page_tinymcemedia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='shared_editors',
            field=models.ManyToManyField(blank=True, help_text='Users who can edit this playlist', related_name='shared_playlists_editable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlist',
            name='shared_readers',
            field=models.ManyToManyField(blank=True, help_text='Users who can view this playlist', related_name='shared_playlists_readonly', to=settings.AUTH_USER_MODEL),
        ),
    ]
