# Generated by Django 5.2.6 on 2025-11-21 12:35

import django.db.models.deletion
import files.models.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_page_tinymcemedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtitle',
            options={'ordering': ['language__title'], 'verbose_name': 'Caption', 'verbose_name_plural': 'Captions'},
        ),
        migrations.AlterModelOptions(
            name='transcriptionrequest',
            options={'verbose_name': 'Caption Request', 'verbose_name_plural': 'Caption Requests'},
        ),
        migrations.AlterModelOptions(
            name='videotrimrequest',
            options={'verbose_name': 'Trim Request', 'verbose_name_plural': 'Trim Requests'},
        ),
        migrations.AddField(
            model_name='media',
            name='linked_playlist',
            field=models.ForeignKey(blank=True, help_text='If set, this Media represents a Playlist in listings', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_representation', to='files.playlist'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_file',
            field=models.FileField(blank=True, help_text='media file', max_length=500, null=True, upload_to=files.models.utils.original_media_file_path, verbose_name='media file'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('image', 'Image'), ('pdf', 'Pdf'), ('audio', 'Audio'), ('playlist', 'Playlist')], db_index=True, default='video', max_length=20),
        ),
    ]
