# Generated by Django 5.2.6 on 2025-12-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('files', '0014_alter_subtitle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_lms_course',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this category represents an LMS course'),
        ),
        migrations.AddField(
            model_name='category',
            name='lti_context_id',
            field=models.CharField(blank=True, db_index=True, help_text='LTI context ID from platform', max_length=255),
        ),
    ]
