# Generated by Django 5.2.6 on 2025-12-24 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('files', '0014_alter_subtitle_options_and_more'),
        ('lti', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_lms_course',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this category represents an LMS course'),
        ),
        migrations.AddField(
            model_name='category',
            name='lti_context_id',
            field=models.CharField(blank=True, db_index=True, help_text='LTI context ID from platform', max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='lti_platform',
            field=models.ForeignKey(
                blank=True, help_text='LTI Platform if this is an LTI course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='lti.ltiplatform'
            ),
        ),
    ]
