# Generated by Django 5.2.6 on 2025-12-29 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('files', '0015_category_is_lms_course_category_lti_context_id'),
        ('lti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='lti_platform',
            field=models.ForeignKey(
                blank=True, help_text='LTI Platform if this is an LTI course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='lti.ltiplatform'
            ),
        ),
    ]
