# Generated by Django 5.2.6 on 2026-04-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0016_category_lti_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediapermission',
            name='source',
            field=models.CharField(choices=[('lti_embed', 'LTI Embed'), ('explicit', 'Explicit')], default='explicit', max_length=32),
        ),
    ]
