# Generated by Django 5.2.6 on 2026-09-27 13:46

from django.db import migrations, models

import files.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0018_embedmediacourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='state',
            field=models.CharField(
                choices=[('private', 'Private'), ('public', 'Public'), ('unlisted', 'Unlisted')], db_index=True, default=files.helpers.get_default_state, help_text='state of Media', max_length=20
            ),
        ),
    ]
