# Generated by Django 5.2.6 on 2026-05-25 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0015_media_external_hls_url'),
        ('files', '0018_embedmediacourse'),
    ]

    operations = [
    ]
