# Generated by Django 5.2.6 on 2026-08-20 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='MigrationService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(choices=[('kaltura', 'Kaltura'), ('panopto', 'Panopto'), ('youtube', 'YouTube')], db_index=True, default='kaltura', max_length=20)),
                ('source_system', models.CharField(blank=True, db_index=True, help_text='Normalised identity of the source installation, derived from the connection', max_length=255)),
                ('connection', models.JSONField(blank=True, default=dict, help_text='Provider credentials, secrets encrypted')),
                ('options', models.JSONField(blank=True, default=dict, help_text='Import options')),
                (
                    'status',
                    models.CharField(
                        choices=[('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('error', 'Error'), ('success', 'Success'), ('aborted', 'Aborted')],
                        db_index=True,
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('cursor', models.JSONField(blank=True, default=dict, help_text='Resume position')),
                ('totals', models.JSONField(blank=True, default=dict, help_text='Discovered and migrated counts per object type')),
                ('log', models.TextField(blank=True, help_text='Phase level events')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Migration',
                'verbose_name_plural': 'Migrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MigrationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('media', 'Media'), ('user', 'User'), ('category', 'Category'), ('caption', 'Caption')], db_index=True, max_length=20)),
                ('source_id', models.CharField(db_index=True, max_length=255)),
                ('target_id', models.IntegerField(blank=True, help_text='pk of the created object, resolved through object_type', null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='success', max_length=20)),
                ('log', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='migrationservice.migrationservice')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['object_type', 'source_id'], name='migrationse_object__4e2a78_idx'),
                    models.Index(fields=['service', 'status'], name='migrationse_service_f021d6_idx'),
                    models.Index(fields=['object_type', 'target_id'], name='migrationse_object__304222_idx'),
                ],
                'unique_together': {('service', 'object_type', 'source_id')},
            },
        ),
    ]
